DROP TYPE IF EXISTS style;
CREATE TYPE style AS ENUM (
    'Mexican',
    'Italian',
    'American',
    'Fancy',
    'Greek'
);

DROP TABLE IF EXISTS restaurant_list;

CREATE TABLE IF NOT EXISTS restaurant_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    price TEXT,
    category style NOT NULL
);

DROP TABLE IF EXISTS favorites_list;

CREATE TABLE IF NOT EXISTS favorites_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    restaurant INTEGER REFERENCES restaurant_list(id) ON DELETE CASCADE,
    users INTEGER REFERENCES feedme_users(id) ON DELETE CASCADE
);

-- SELECT restaurant_list.title, favorites_list.id, restaurant_list.id
-- FROM restaurant_list
-- INNER JOIN favorites_list ON restaurant_list.id=favorites_list.id
